### ISSUE TITLE
Suggestion: Guide as a PDF

### ISSUE THREAD

**Issue by Devlonoah** [devonfw-forge/devonfw4flutter#16]
This is not an issue.But a suggestion that

This awesome guides could be turned to pdf,
Thanks.

**Comment by Fasust** [comment]
Hey @Devlonoah 👋🏻 Thank you for the suggestion.
[This .md file](https://github.com/devonfw-forge/devonfw4flutter/blob/master/.raw-text/gfm-guide.md) includes the full content of the guide. It's created as a side effect of how we automatically generate the citations & refernces section. You Can use an [md to pdf converter](https://www.markdowntopdf.com/) to turn it into a pdf if that is more convenient for you then having it in a wiki.

**Comment by Fasust** [comment]
Pinning this for future reference
